# Generated by Django 4.2.7 on 2023-11-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2000-06-12'),
            preserve_default=False,
        ),
    ]
